### ISSUE TITLE
Merge wip into master?

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/prebuild-install#1]

**Comment by juliangruber** [comment]
since master is empty, +1

**Comment by mathiask88** [comment]
If you are done with reviewing +1. The readme could be improved, but that's also fine if it's done in master.

**Comment by ralphtheninja** [comment]
I'm not done reviewing, but I can do that on master branch as well ;)

**Comment by ralphtheninja** [comment]
But maybe merge https://github.com/mafintosh/prebuild-install/pull/2 first
