### ISSUE TITLE
Automatically install devDependencies on failure

### ISSUE THREAD

**Issue by piranna** [mafintosh/prebuild-install#11]
If a prebuild file is not found or the download fails, automatically install the module devDependencies so the fallback command can be correctly executed. This way it's not required to install the dependencies needed to build the module when exists a good prebuild candidate.

**Comment by juliangruber** [comment]
do you use something else than `node-gyp` for the fallback command?

**Comment by piranna** [comment]
Yes, I'm using some custom bash scripts since for NodeOS I'm downloading, compiling and packing some utilities commands like [qemu](https://github.com/NodeOS/qemu/blob/raspi/scripts/BigRedButton), [genext2fs](https://github.com/NodeOS/genext2fs/blob/master/scripts/build) or [genfatfs](https://github.com/NodeOS/genfatfs/blob/master/scripts/build).

**Comment by juliangruber** [comment]
ok,installing devDependencies on failure then sounds good to me. what do @ralphtheninja and @mafintosh think?

**Comment by piranna** [comment]
Good :-) I know it could be done just by adding `npm install` to the fallback option, only that this would lead to an infinite loop. I don't know if there's an npm option to only install dependencies, I think it's `--no-scripts`, but this leads to a really long and ugly string, that's why I asked about adding that functionality to `prebuild-install` itself, if not as default behaviour maybe it would be added as an opt-in flag, what do you think?

**Comment by juliangruber** [comment]
actually i think something like this would be fine: `prebuild-install || npm install --no-scripts && npm run build`

**Comment by piranna** [comment]
> actually i think something like this would be fine: prebuild-install || npm install --no-scripts && npm run build

Yes, that's what I was talking about on my last post, but seems to me that's too much verbose, specially when having a custom download URL.

**Comment by ralphtheninja** [comment]
> ok,installing devDependencies on failure then sounds good to me. what do @ralphtheninja and @mafintosh think?

+1 if it can help out `NodeOS` and ss not frowned upon. I have never done anything like that before.

> actually i think something like this would be fine: prebuild-install || npm install --no-scripts && npm run build

I didn't know about `--no-scripts`. Cool!

**Comment by mafintosh** [comment]
👎 on having this module download devDependencies. use the `||` line linked above or add the deps as production dependencies (i'd personally do the latter).

**Comment by juliangruber** [comment]
ok, let's close this then. verbosity is good :)

**Comment by piranna** [comment]
> ok, let's close this then. verbosity is good :)

Sort of, I opened this issue in part as a discussion about how this topic could be achieved. Having the build dependencies set as `dependencies` would be suboptimal, but seems to be the best option.
