### ISSUE TITLE
Make tests windows friendlier

### ISSUE THREAD

**Issue by mathiask88** [mafintosh/prebuild-install#14]
The tests are currently not working on windows platforms.
- [x] We need windows builds in `a-native-module` (I can build and upload them)
- [x] Make some tests language/platform aware e.g. [This](https://github.com/mafintosh/prebuild-install/blob/master/test/download-test.js#L277)

**Comment by juliangruber** [comment]
+1!

**Comment by ralphtheninja** [comment]
def +1

**Comment by mathiask88** [comment]
#23 fixes the tests

@ralphtheninja It would be nice if you could add ABI 47/48/51 in [a-native-module](https://github.com/ralphtheninja/a-native-module/releases) for win32/64

**Comment by ralphtheninja** [comment]
@mathiask88 Added you as collaborator so you should be able to add them yourself.

**Comment by ralphtheninja** [comment]
If that doesn't work for you I can always add them myself. Let me know :)
