### ISSUE TITLE
Error:  unregistered users are not allowed to access package @lgeiger/prebuild-install : @lgeiger/prebuild-install

### ISSUE THREAD

**Issue by AnandNidamanuru** [mafintosh/prebuild-install#20]
Hi,

when trying to install zeromq in windows,  I am getting the below error.
Below is the error log.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\program files\\nodejs\\node.exe" "C:\\program files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "zeromq" "-g"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code E403

npm ERR! unregistered users are not allowed to access package @lgeiger/prebuild-install : @lgeiger/prebuild-install
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

Please let us know how to resolve the issue

**Comment by AnandNidamanuru** [comment]
Apologies for opening the issue. This is due to a private registry i was using.
After this i had to remove proxy and reinstall. Then it started working.
So closing the issue

**Comment by lgeiger** [comment]
@AnandNidamanuru Glad to hear you got it working.
`@lgeiger/prebuild-install` uses the code of #19. Please comment there if you experience more issues.
