### ISSUE TITLE
[regression] changes overwritten after sync with `prebuild`

### ISSUE THREAD

**Issue by piranna** [mafintosh/prebuild-install#24]
The [sync with prebuild](https://github.com/piranna/prebuild-install/commit/d6e6d7e196a99e3ad86ee0fdcd31974a91aa8451) has reverted some changes applied on `prebuild-install` like the [removal of check for invalid tarfile](https://github.com/piranna/prebuild-install/commit/7e8ad6cbd383623ad98cf9c3a130583c92d74a50), as can be seen on the [unpack()](https://github.com/mafintosh/prebuild-install/blob/1a43f36c6e1c65d1595ccffebca2868cee39c8c4/download.js#L98). This fixes should be re-added, and a solution should be searched to prevent this overwrittes in the future, being the more practical one the [removal of duplicated code between both projects](https://github.com/mafintosh/prebuild/issues/148).

**Comment by lgeiger** [comment]
> The sync with prebuild has reverted some changes applied on prebuild-install like the removal of check for invalid tarfile, as can be seen on the unpack().

Sorry for that. I assumed that `prebuild` is up to date but https://github.com/mafintosh/prebuild/pull/111 wasn't merged so I missed this one.

> This fixes should be re-added

Done in #25 

> a solution should be searched to prevent this overwrittes in the future, being the more practical one the removal of duplicated code between both projects.

Done in https://github.com/mafintosh/prebuild/pull/160

**Comment by piranna** [comment]
> Sorry for that. I assumed that prebuild is up to date but mafintosh/prebuild#111 wasn't merged so I missed this one.

Ok, maybe this is the kind of things it was told that both `prebuild` and `prebuild-install` source code where diverging...


> This fixes should be re-added
> Done in #25

Thanks dude! :-)


> a solution should be searched to prevent this overwrittes in the future, being the more practical one the removal of duplicated code between both projects.
> Done in mafintosh/prebuild#160

Cool :-) Maybe we should re-sync to be sure there's nothing left? I could be done after it got merged to prevent any other missed commit there...

**Comment by piranna** [comment]
I have just review it and commits https://github.com/mafintosh/prebuild-install/commit/09eb7805108b9e2cef8c99e52001604448b2090c and https://github.com/mafintosh/prebuild-install/commit/eff516c54252c25123e6a4f38e89664eed93f3ab have been overwritten too, It was 3AM when I opened the issue and forgot to review this things. I'm not sure if other things from other contributors would have been missed too, these are just mine ones, maybe it would be good to do a review of the commit that introduced the regression to look for other missed things...

**Comment by lgeiger** [comment]
> I have just review it and commits 09eb780 and eff516c have been overwritten too

Fixed in #26 

> I'm not sure if other things from other contributors would have been missed too

I've gone through the old PRs on `prebuild-install` and checked that no other changes have been overwritten.

**Comment by piranna** [comment]
Thank you :-) When they could be published on npm? Maybe after the review of the other pull-request?
