### ISSUE TITLE
Suggested `install` script breaks on Windows

### ISSUE THREAD

**Issue by oleavr** [mafintosh/prebuild-install#30]
In README.md it is suggested to set the package.json install script to:
```
...
  "scripts": {
    "install": "prebuild-install || node-gyp rebuild"
  }
...
```

The `||` part is however not portable to Windows, so packages that need to be installable on Windows will need an install script written in JavaScript. (Unless I'm missing something obvious, which is likely.)

**Comment by mathiask88** [comment]
`||` does work in windows CMD but not in powershell.

**Comment by oleavr** [comment]
Yeah I was barking up the wrong tree. Sorry for the false alarm.
