### ISSUE TITLE
consider bailing out on download if installing inside cloned repo

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/prebuild-install#8]
In `prebuild` we added the following check to force a compile when developing:

```js
if (rc.install) {
  if (!(typeof pkg._from === 'string')) {
    // From Git directly
    rc.compile = true
  } else if (pkg._from.length > 4 && pkg._from.substr(0, 4) === 'git+') {
    // From npm install git+
    rc.compile = true
  } else {
    // From npm repository
    rc.download = rc.install
  }
}
```

from https://github.com/mafintosh/prebuild/blob/master/bin.js#L48-L59

Now, since this module doesn't have the code for compiling, it could basically just do `process.exit(1)` (instead of setting `rc.compile` etc) and tack on a `.. || node-gyp rebuild` just like the README shows to make this work.

**Comment by mathiask88** [comment]
I pushed a PR but I want to mention that developer could also use the `--no-prebuild` flag while developing, so I have no strong opinion on this one.
