### ISSUE TITLE
Proxy support 

### ISSUE THREAD

**Issue by mathiask88** [mafintosh/prebuild-install#9]
Isn't it enough to give simple-get an option object with the proxy as the host and the url as path?

**Comment by ralphtheninja** [comment]
> Isn't it enough to give simple-get an option object with the proxy as the host and the url as path?

Afaik simple-get wraps the http module. Does it have support for proxies?

**Comment by mathiask88** [comment]
You can use 
```
var http = require("http");

var options = {
  host: "proxy",
  port: 8080,
  path: "http://www.google.com",
  headers: {
    Host: "www.google.com"
  }
};
http.get(options, ...
```
for HTTP requests. And AFAIK it is also possible to access HTTPS sites but then the connection to the proxy is still HTTP.

**Comment by rgbkrk** [comment]
One of our users (@eskemojoe007) is [running into this with Hydrogen](https://github.com/nteract/hydrogen/issues/558#issuecomment-268896422). I tried to have them run `npm install zeromq` directly and it ran into problems. Just to make sure it's not something specific we did in `zeromq`, we'll check out `leveldown`.

**Comment by mathiask88** [comment]
#13
